- title: Trust & Credibility
  description: 85% of people trust online reviews as much as personal recommendations
  image: assets/images/shield.svg
- title: Customer Acquisition
  description: 94% of consumers report positive reviews make them more likely to use a business 
  image: assets/images/acquisition.png
- title: Higher Revenue
  description: Increasing a review rating by 1-star could mean a 5-9% increase in revenue
  image: assets/images/revenue.png
